name: fresh_flutter
description: A fresh flutter app template

version: 1.0.0+1

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  provider: ^4.1.1
  flutter_fimber: ^0.4.2
  flutter_vector_icons: ^0.2.1
  flutter_svg: ^0.17.4
  padder: ^1.3.0
  shared_preferences: ^0.5.7+2
  streaming_shared_preferences: ^1.0.1
  get_it: ^4.0.2
  rxdart: any
  auto_size_text: ^2.1.0
  after_layout: ^1.0.7+2
  url_launcher: ^5.4.7
  kt_dart: ^0.7.0+1
  intl: any
  dio: ^3.0.9
  dio_flutter_transformer: ^3.0.2
  tuple: any
  package_info: ^0.4.0+18
  flutter_advanced_networkimage: ^0.7.0
  system_proxy: ^0.0.1
  keel: ^0.0.5
#  firebase_crashlytics: ^0.1.0+3
#  firebase_analytics: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true